name: Decompile APK with Apktool

on:
  workflow_dispatch:

jobs:
  decompile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget unzip openjdk-17-jre

      - name: Download Apktool 3.0.1
        run: |
          wget https://github.com/iBotPeaches/Apktool/releases/download/v3.0.1/apktool_3.0.1.jar -O apktool.jar
          wget https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool -O apktool
          chmod +x apktool

      - name: Download APK ZIP
        run: |
          wget https://protomines.ddns.net/apk/MapWorld-apk.zip -O app.zip

      - name: Extract APK
        run: |
          unzip app.zip -d extracted

      - name: Find APK file
        id: find_apk
        run: |
          APK_PATH=$(find extracted -name "*.apk" | head -n 1)
          echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT

      - name: Decompile APK
        run: |
          mkdir -p output
          java -jar apktool.jar d "${{ steps.find_apk.outputs.apk_path }}" -o output

      - name: Upload Decompiled Files
        uses: actions/upload-artifact@v4
        with:
          name: decompiled-apk
          path: output
